import os
import time
import datetime
import getpass
import socket
os.system("clear")
s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
s.connect(('8.8.8.8',80))
ip=s.getsockname()[0]
print("OOOPS你没有激活!")
print("了解FlyOS完整版的魅力？")
print("FlyOS Console有限制功能的预览:")
os.system("toilet -f mono12 -F gay FlyOS")
print("__________________________")
print("________FlyOS vx.xx________")
#获取年月日格式的时间
date = time.strftime("%Y-%m-%d %H:%M:%S")
print("现在时间:" + date)
i = datetime.datetime.now()
PREFIX='''\n日　期：{}年{}月{}日 时　间：{} \n'''.format(i.year,i.month,i.day,time.strftime('%p %X'))
print(PREFIX)
print(f"{getpass.getuser()}欢迎使用FlyOS!")

try:
    print(requests.get("http://flyosgeek.com/notices.txt").content.decode("utf-8"))
except Exception:
    print("获取公告失败")

print("欢迎使用FlyOS开源面板！")
print("By:XingYuJie Rainbow")
print("FlyOS由Microtech开发")
print("输入00查看关于")
print("输入01反馈问题")
print("输入02快速更新")
print("输入03切换更新通道")
print("输入04完整更新")
print("1.给FlyOS 安装GNU/发行版Linux(推荐|简洁)")
print("2.Linux菜单高级部署菜单(推荐)")
print("3.软件安装器(Termux软件包)")
print("4.启动最近使用的GNU/Linux")
print("5.FlyOS Chat 飞聊聊天系统")
print("6.重新查看激活状态/重启")
print("7.更新软件源APT")
print("8.更新软件源PKG")
print("9.查看系统信息")
print("10.更改默认Shell解释器")
print("11.更改Termux密码")
print("12.FlyOS浏览器")
print("13.网站服务器面板")
print("14.重新启动FlyOS WEB Panel(已自动启动，再次启动会出问题)")
print("15.打开Aria2")
print("16.打开Aria2 WEB")
print("17.VM虚拟机")
print("18.文件管理器")
print("19.虚拟机WEB管理面板(已自动启动，再次启动会出问题)")
print("20.启动nginx WEB Server")
print("21.初始化FlyOS")
print("22.启动Xfce4图形化(端口5902)")
print("23.启动Minecraft-pocketmine服务器")
print("更多的功能............")
print("0.进入终端")
print("如需再次打开FlyOS Console，进入终端输入flyos即可")
print("####FlyOS Panel已经启动，请使用手机网络浏览器或者其他设备访问http://" + ip + ":8888，VNC桌面环境请使用VNC客户端连接到" + ip + ":5902")
print("!!序号使用帮助:请在下面🚀后输入要启动的编号，例如1")
print(f"👉👉👉👉👉👉👉👉{getpass.getuser()}🌈")
print("/data/data/com.termux/files/home/")
print("✈️ " + date + "🚀🚀🚀 >>> ")
print("怎么样，激活专业版体验以上功能!")
print("__________________________________")
print("去http://store.flyosgeek.com购买密钥!")
input("按下回车开始激活")
os.system("python $FLYOS/kernel/boot/active/check.py")