#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
	update-alternatives --remove w /usr/bin/w.procps
    ;;
  upgrade|failed-upgrade)
    ;;
esac

# Automatically added by dh_installdeb/12.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/protect-links.conf 2:3.3.16-1ubuntu1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/10-link-restrictions.conf 2:3.3.16-1ubuntu1\~ -- "$@"
# End automatically added section


exit 0

